### Get book data from the catalog 
GET http://localhost:41181/rest/catalog/Books


### Submit an order
POST  http://localhost:41181/rest/catalog/submitOrder HTTP/1.1
Content-Type: application/json

{
   "book": 1,
   "quantity": 95
}